[package]
name = "send-request"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
axum = { version = "0.8.6", default-features = false, features = ["macros"] }
http = "1.3.1"
spin-sdk = { path = "../..", features = ["wasip3-unstable"] }
