[package]
name = "wasi-http-rust-streaming-outgoing-body"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.100"
futures = "0.3.31"
hex = "0.4.3"
sha2 = "0.10.9"
url = "2.5.7"
spin-sdk = { path = "../.." }
