#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "competing-outbound-http-calls"
version = "0.1.0"
authors = ["The Spin project"]
description = "Demonstrates making competing outbound HTTP calls in WASIp3"

[[trigger.http]]
route = "/..."
component = "competing-outbound-http-calls"
executor = { type = "wasip3-unstable" }

[component.competing-outbound-http-calls]
source = "target/wasm32-wasip2/release/competing_outbound_http_calls.wasm"
allowed_outbound_hosts = [
    "https://spinframework.dev",
    "https://component-model.bytecodealliance.org/",
]
[component.competing-outbound-http-calls.build]
command = "cargo build --target wasm32-wasip2 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
